networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_PATH}/wordpress
      o: bind
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUMES_PATH}/mariadb
      o: bind

services:
  mariadb:
    build:
      context: requirements/mariadb/
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    image: mariadb
    container_name: mariadb
    restart: on-failure
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    build:
      context: requirements/nginx
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    environment:
      - DOMAIN_NAME
    depends_on:
      - wordpress
    ports:
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-f", "https://${DOMAIN_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    build:
      context: requirements/wordpress
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - WP_ROOT_USER=${WP_ROOT_USER}
        - WP_ROOT_EMAIL=${WP_ROOT_EMAIL}
        - WP_ROOT_PASSWORD=${WP_ROOT_PASSWORD}
        - WP_USER=${WP_USER}
        - WP_EMAIL=${WP_EMAIL}
        - WP_PASSWORD=${WP_PASSWORD}
    image: wordpress
    container_name: wordpress
    restart: on-failure
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - WP_ROOT_USER
      - WP_ROOT_EMAIL
      - WP_ROOT_PASSWORD
      - WP_USER
      - WP_EMAIL
      - WP_PASSWORD
    depends_on:
      mariadb:
        condition: service_healthy
